// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeXQUDhBxqHi4-vkbUTuS3Ra72jabQvpU',
    appId: '1:115380763567:web:53df19104fc65533284d5a',
    messagingSenderId: '115380763567',
    projectId: 'it-project-4b',
    authDomain: 'it-project-4b.firebaseapp.com',
    storageBucket: 'it-project-4b.appspot.com',
    measurementId: 'G-LJXZVS3X78',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxs2RMHP0onJEdGhmN1iSaUPHHOACMqjY',
    appId: '1:115380763567:android:8e0b988fcafaa2bd284d5a',
    messagingSenderId: '115380763567',
    projectId: 'it-project-4b',
    storageBucket: 'it-project-4b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADvmFAwNZ3JSIRz16mupUCk_rxtp-5zHM',
    appId: '1:115380763567:ios:5bfe8ad0f1bc79a2284d5a',
    messagingSenderId: '115380763567',
    projectId: 'it-project-4b',
    storageBucket: 'it-project-4b.appspot.com',
    iosBundleId: 'com.example.ipj417cB2024',
  );
}
